### PR TITLE
Update server.sls

### PR DESCRIPTION
**Pull request by abednarik**
Add grafana repository when including server.sls to install a recent version.

### CODE REVIEW

**Comment by cloudlab-autobuild** [comment]
Can one of the admins verify this patch?

**Comment by abednarik** [comment]
Reference ::  https://grafana.com/grafana/download 
For Debian family distributions, is always the same repo url, even in Ubuntu jesse distro name is used, which is a litle bit weird, that's why I think that link helps to understand this.

**Comment by abednarik** [comment]
Ok, sorry.

**Comment by simonpasquier** [comment]
@abednarik no problem, thanks for your time anyway.

**Comment by syphernl** [comment]
It would probably be a good idea to include a `repo.sls` anyways that can be included. IMHO it makes no sense to have dependencies to other formulas. Grafana cannot be installed without the repo, but the repo isn't added by this formula.

**Pull request closed without merging**
